### ISSUE TITLE
Throw a ready DLL file into the release

### ISSUE THREAD

**Issue by d3adwolf** [PandahutMushy/BookmarkHostPlugin#1]
Thanks for the plugin, but I for one don't particularly program in C# to keep Visual Studio on an arm64 macbook. Can I have a ready-made file for this case?)

**Comment by PandahutMushy** [comment]
I've uploaded an initial release. I am sorry for not having posted one earlier. Thank you for the reminder!

https://github.com/PandahutMushy/BookmarkHostPlugin/releases/tag/Initial

**Comment by PandahutMushy** [comment]
> Thanks for the plugin, but I for one don't particularly program in C# to keep Visual Studio on an arm64 macbook. Can I have a ready-made file for this case?)

I've uploaded an initial release. I am sorry for not having posted one earlier. Thank you for the reminder!

https://github.com/PandahutMushy/BookmarkHostPlugin/releases/tag/Initial
